apiVersion: v1
kind: PersistentVolume
metadata: 
  name: jsstorage
  labels:
    app: jswebsite-storage
    purpose: Task3
    status: Completed
spec:
  storageClassName: manual  
  capacity:
    storage: 2Gi
  accessModes:    
    - ReadWriteOnce  
  hostPath:
    path: "/tmp/hostpath-provisioner/pvc-ef48571b-c7d6-49a6-8ab6-49911ab03483/workspace/job1"
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  